---
- include_vars: '{{ openstack_release }}.yml'

- name: Install yum-plugin-priorities
  yum: name=yum-plugin-priorities state=installed enablerepo=ol7_optional_latest  

- name: Setup Openstack Yum Repository
  yum: name={{ openstack_yum_repo_file }} state=installed
  
- name: Install Openstack SELinux
  yum: name=openstack-selinux state=installed
 
#- name: Update System
#  yum: name=* state=latest
#  when: ansible_os_family == "RedHat"  